[[redirects]]
  from = "http://seamc.it/*"
  to = "https://seamc.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.seamc.it/*"
  to = "https://seamc.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.seamc.it/*"
  to = "https://seamc.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
